version: '3.1'

services:
  app:
    image: finpress
    restart: always
    ports:
      - 8080:80
    environment:
      finpress_DB_HOST: db
      finpress_DB_USER: exampleuser
      finpress_DB_PASSWORD: examplepass
      finpress_DB_NAME: exampledb
    volumes:
      - ..:/workspace:cached

  db:
    image: mariadb
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: exampledb
      MYSQL_USER: exampleuser
      MYSQL_PASSWORD: examplepass
      MYSQL_RANDOM_ROOT_PASSWORD: '1'
    volumes:
      - db:/var/lib/mysql

volumes:
  db:
